SDK=../SDK
INCLUDES=-I. -I$(SDK)/CHeaders/XPLM -I$(SDK)/CHeaders/Widgets

# platform independent defines
DEFINES=

SOURCES_CPP=sbh.cpp ofp_get_parse.cpp http_get.cpp log_msg.cpp
SOURCES_C=

# the c++ standard to use
CXXSTD=-std=c++20

OPT=-O3
